version: '3'
services:
  demo:
    image: nokiatesting/docker_demo:mysql
    ports:
      - "5000:5000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5
    command: ['/bin/sh', '-c', 'MYSQL_PWD=root mysql -uroot -e "create database if not exists testdb" || exit 1']
    volumes:
      - "mydata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - testnet

volumes:
  mydata:
  
networks:
  testnet:
