version: '3'
services:
  mysql:
    image: mysql:5
    restart: always
    volumes:
      - "mydata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  demo:
    image: nokiatesting/docker_demo:mysql
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mydata:
