version: '3'
services:
  demo:
    image: nokiatesting/docker_demo:mysql
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - testnet
  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    volumes:
      - "mydata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - testnet

volumes:
  mydata:
  
networks:
  testnet:
