version: '3'
services:
  demo:
    image: nokiatesting/docker_demo:mysql
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      -type: volume
       source: mydata
       target: /var/lib/mysql
    networks:
      testnet
